### PR TITLE
Update eeprom-board.c

### PR DESCRIPTION
**Pull request by QINLIMIN**
Hi @sandeepmistry, this code which have been test, it can store and restore nvm data properly.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @QINLIMIN,

Thanks for the pull request!

Are there any advantages to the changes you proposed here compared to the pull request I created in #6 earlier?

**Comment by QINLIMIN** [comment]
Hi @sandeepmistry, I tried to build #6 and download to hw board, it can't work properly, have you test it before pushing?

**Comment by sandeepmistry** [comment]
Hi @QINLIMIN,

Sorry for the delay, the changes in #6 are working for me in my testing.

However, I'm getting some linker errors when trying to compile this pull request:

```
/Users/sanmis01/Downloads/gcc-arm-none-eabi-10-2020-q4-major-mac/Payload/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /Users/sanmis01/Downloads/gcc-arm-none-eabi-10-2020-q4-major-mac/Payload/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/pico_lorawan_otaa_temperature_led.dir/__/__/src/lorawan.c.obj: in function `lorawan_init':
CMakeFiles/pico_lorawan_hello_otaa.dir/__/__/src/lorawan.c.objlorawan.c:: in function `(lorawan_init.text.lorawan_init':
+0xlorawan.c:a().text.lorawan_init: undefined reference to `+0xEepromMcuInita'
): undefined reference to `EepromMcuInit'
/Users/sanmis01/Downloads/gcc-arm-none-eabi-10-2020-q4-major-mac/Payload/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /Users/sanmis01/Downloads/gcc-arm-none-eabi-10-2020-q4-major-mac/Payload/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/pico_lorawan_otaa_temperature_led.dir/__/__/src/lorawan.c.obj: in function `OnNvmDataChange':
CMakeFiles/pico_lorawan_hello_otaa.dir/__/__/src/lorawan.c.obj: in function `lorawan.c:OnNvmDataChange(':
.text.OnNvmDataChange+0xlorawan.c:/Users/sanmis01/Downloads/gcc-arm-none-eabi-10-2020-q4-major-mac/Payload/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/lda(: ).text.OnNvmDataChange: undefined reference to `+0xEepromMcuFlusha'
): undefined reference to `EepromMcuFlush'
CMakeFiles/pico_lorawan_hello_abp.dir/__/__/src/lorawan.c.obj: in function `lorawan_init':
lorawan.c:(.text.lorawan_init+0xa): undefined reference to `EepromMcuInit'
/Users/sanmis01/Downloads/gcc-arm-none-eabi-10-2020-q4-major-mac/Payload/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/pico_lorawan_hello_abp.dir/__/__/src/lorawan.c.obj: in function `OnNvmDataChange':
lorawan.c:(.text.OnNvmDataChange+0xa): undefined reference to `EepromMcuFlush'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[2]: make[2]: make[2]: *** [examples/otaa_temperature_led/pico_lorawan_otaa_temperature_led.elf] Error 1*** [examples/hello_abp/pico_lorawan_hello_abp.elf] Error 1*** [examples/hello_otaa/pico_lorawan_hello_otaa.elf] Error 1


make[1]: *** [examples/hello_otaa/CMakeFiles/pico_lorawan_hello_otaa.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [examples/hello_abp/CMakeFiles/pico_lorawan_hello_abp.dir/all] Error 2
make[1]: *** [examples/otaa_temperature_led/CMakeFiles/pico_lorawan_otaa_temperature_led.dir/all] Error 2
[100%] Built target pico_lorawan_default_dev_eui
make: *** [all] Error 2
```

For now, I'll go ahead and merge #6. If the `main` branch is still now working for you after merging, please let me know and we can revisit this pull request.

**Comment by sandeepmistry** [comment]
Sorry, I've accidentally merged this by mistake instead of #6. I've had to for force push `main` to fix.

**Pull request merged**
